name = input("Enter your name : ")
age = int(input("Enter your age : "))
city = input("Enter your city name : ")
grade = int(input("Enter your grade : "))
hungry = bool(input("Are you hungry? Answer in True or False : "))
print(f"Hi {name}. You are {age}years old. Your from {city}. You are in grade {grade}")
print(f"You are hungry {hungry}.")
print(type(name))
print(type(age))
print(type(city))
print(type(grade))
print(type(hungry))