name1 = input("Enter your name : " )
age1 = input("Enter your age : " )
name2 = input("Enter your name : " )
age2 = input("Enter your age : " )
name3 = input("Enter your name : " )
age3 = input("Enter your age : " )
name4 = input("Enter your name : " )
age4 = input("Enter your age : " )
name5 = input("Enter your name : " )
age5 = input("Enter your age : " )
print(f"Hi {name1}. You are {age1}years old.")
print(f"Hi {name2}. You are {age2}years old.")
print(f"Hi {name3}. You are {age3}years old.")
print(f"Hi {name4}. You are {age4}years old.")
print(f"Hi {name5}. You are {age5}years old.")