nameS1 = input("Enter your name :")
ageS1 = input("Enter your age :")
nameS2 = input("Enter your name :")
ageS2 = input("Enter your age :")
nameS3 = input("Enter your name :")
ageS3 = input("Enter your age :")
nameS4 = input("Enter your name :")
ageS4 = input("Enter your age :")
nameS5 = input("Enter your name :")
ageS5 = input("Enter your age :")
print(f"Hi Student 1{nameS1}. Your age is {ageS1}")
print(f"Hi Student 2{nameS2}. Your age is {ageS2}")
print(f"Hi Student 3{nameS3}. Your age is {ageS3}")
print(f"Hi Student 4{nameS4}. Your age is {ageS4}")
print(f"Hi Student 5{nameS5}. Your age is {ageS5}")
